### ISSUE TITLE
focus new windows

### ISSUE THREAD

**Issue by netfun81** [henriquegogo/weema#1]
Nice minimal window manager.  It's near perfect however when you open a new program it doesn't give the new window focus and requires alt-button1 to focus it.   It seems like it would not be too difficult to implement but I haven't looked into it.

**Comment by henriquegogo** [comment]
Actually it's not so simple and I don't know why, Google Chrome gets focus for him (it's another problem). Focus it's my biggest headache in this tiny project

**Comment by henriquegogo** [comment]
I found in your repos that you have some wm code. How did you solve that focus problem? BTW, I did a lot of changes in my code and have a lot of improvements

**Comment by henriquegogo** [comment]
Solved in commit https://github.com/henriquegogo/weema/commit/e8036cc9d8703d21916644dc277598c63ce86bdb
Detecting when a window is mapped and then focus

**Comment by henriquegogo** [comment]
I know that was already fixed, but in commit https://github.com/henriquegogo/weema/commit/a2d2b8b268d45a89a5fe9dad27c66337395c42ce I implemented the focus/raise without move cursor.
