### ISSUE TITLE
Feature request: Virtual Desktops

### ISSUE THREAD

**Issue by netfun81** [henriquegogo/weema#2]
This project keeps getting better.  Any chance to get virtual desktops implemented?

**Comment by henriquegogo** [comment]
I think it's not so difficult to implement that, but I need to make the current version stable before to implement this.

BTW, did you tried after my new commits? After you comment I made the major refactoring in window positioning behavior. I hope you enjoy.

**Comment by henriquegogo** [comment]
It's not in my plans. Maybe in a future. For now the focus is simplicity and usability
